apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: monitoring
  name: monitoring

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd

spec:
  project: default
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com/'
    targetRevision:  8.5.11
    chart: prometheus-operator

    helm:
      values: |

        prometheusOperator:
          enabled: false

        prometheus:
          enabled: false

        alertmanager:
          enabled: false

        grafana:
          enabled: false
          defaultDashboardsEnabled: true
          adminPassword: prom-operator

        nodeExporter:
          enabled: false

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

